### ISSUE TITLE
Test/document `gulp` usage in non-Docker dev

### ISSUE THREAD

**Issue by tobiasmcnulty** [caktus/etlman#121]
It looks like our `gulpfile.js` is missing [the code](https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/gulpfile.js#L173-L183) that actually calls `runServer()`, and possibly other things. We should compare it again to the django-cookiecutter template, update as needed, and document the commands one needs to run to get static assets building locally.

As a temporary workaround, you can run `gulp` in a separate shell (but you'll still need to run and access `python manage.py runserver` manually on port 8000, not port 3000).

A/C:

- [ ] Port 3000 does not render the site before this fix
- [ ] Port 3000 renders the site after the fix

**Comment by ronardcaktus** [comment]
Moving this to the backlog because I am running the application in docker and therefore can't access port 3000.

**Comment by tobiasmcnulty** [comment]
Obsolete since we are moving to webpack. /CC @janelle-caktus
