### ISSUE TITLE
Update URL structure to include Project ID

### ISSUE THREAD

**Issue by tobiasmcnulty** [caktus/etlman#59]
With the project switcher in the nav bar, the selection should be sticky.

It would be best not to store this in the session, which might lead to confusing behavior between tabs.

Better would be to include the project ID in the URL and nest any project-specific URLs under that, e.g.:

```
projects/<int:pk>/pipelines/  # list page
projects/<int:pk>/pipelines/new/  # create page
projects/<int:pk>/pipelines/<int:pk/  # edit page
```

A/C:

- [x] Once a project is selected, "Projects" text in nav bar changes to show current project name instead
- [x] Current project is marked as `active` in the nav bar(if possible, I can't tell if `active` works for dropdown menus from the docs, or not): https://getbootstrap.com/docs/4.0/components/navbar/#nav
- [x] Each project link name in the dropdown menu takes the user to the pipeline list page for that project

**Comment by wfzyx** [comment]
This was merged with #43
