### ISSUE TITLE
Add `sql_query` field to `DataInterface` model

### ISSUE THREAD

**Issue by tobiasmcnulty** [caktus/etlman#88]
A/C:

- [x] "SQL query" TextField appears below "Connection string" field on step one of the Add/edit pipeline form. It should be the same size as the connection string field
- [x] Adding new and editing existing pipelines works with the new field
- [x] Nice to have: "Database" is selected by default when creating a new pipeline (try passing `initial={"interface_type": "database"}` when instantiating the form for the first time in the `GET` request)
- [x] Nice to have: Shorten the "Connection string" to about 3 rows, like so:

![Screen Shot 2022-08-31 at 9 50 45 AM](https://user-images.githubusercontent.com/160132/187694992-8931adeb-63ce-437b-8128-eb72831df89c.png)

**Comment by ronardcaktus** [comment]
Working in the admin

![Image](https://user-images.githubusercontent.com/87770895/187712119-630c39b8-f055-40de-a1db-cea65fc0a62b.png)
