### ISSUE TITLE
Test the pipeline step (script)

### ISSUE THREAD

**Issue by tobiasmcnulty** [caktus/etlman#90]
A/C:
- [x] Add "Test Script" button to step 2 in the add pipeline wizard
- [x] The "Test Script" button sends the form data to the server through an `hx-post` (like on step 1)
- [x] The view returns 
    - [x] an HTML div with the results from the script (refer to wireframes from @janelle-caktus), with placeholder results for now ("0" for exit status and 5-10 lines from the runserver logging as the script output), place the script output in a `text-monospace` p tag: https://getbootstrap.com/docs/4.1/utilities/text/#monospace, and
    - [x] the validated form HTML (via hx OOB div, like step 1)
~~- [ ] User cannot click the next/save button until they test the script and the exit status is 0~~

**Comment by ronardcaktus** [comment]
This looks like a good possible solution, https://www.encodedna.com/javascript/practice-ground/default.htm?pg=javascript_disabled_property along with https://stackoverflow.com/questions/6008908/use-django-template-tags-in-jquery-javascript
